[project]
name = "mino-music-engine"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "renup0502-svg", email = "renup0502@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mino-music-engine = "mino_music_engine.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
